version: 2

models:
  - name: fact_cycling_activities
    description: "Core fact table for virtual cycling activities with calculated training metrics"
    columns:
      - name: activity_id
        description: "Unique identifier for each activity"
        tests:
          - unique
          - not_null
      - name: avg_hr
        description: "Average Heart Rate"
        tests:
          - not_null
      
      - name: activity_date
        description: "Date of activity"
        tests:
          - not_null
      
      - name: athlete_id
        description: "Foreign key to dim_athlete"
        tests:
          - not_null
          - relationships:
              to: ref('dim_athlete')
              field: athlete_id
      
      - name: ftp_id
        description: "Foreign key to dim_ftp for historical FTP tracking"
        tests:
          - relationships:
              to: ref('dim_ftp')
              field: ftp_id
      
      - name: duration_minutes
        description: "Activity duration in minutes"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      
      - name: intensity_factor
        description: "Ratio of normalized power to FTP (should be 0-2 for valid activities)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 3
              inclusive: true
      
      - name: tss
        description: "Training Stress Score"
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"

  - name: dim_ftp
    description: "SCD Type 2 dimension tracking FTP changes over time"
    columns:
      - name: ftp_id
        tests:
          - unique
          - not_null
      
      - name: athlete_id
        tests:
          - not_null
      
      - name: ftp_watts
        tests:
          - not_null
          - dbt_utils.accepted_range:
              max_value: 500  

      - name: test_date
        tests:
          - dbt_utils.expression_is_true:
              expression: " > '2025-12-12'"